services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ironkey
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: apps/desktop/dockerfile.web
    restart: "no"
    ports:
      - "5173:80"
    environment:
      - DOCKER_BUILDKIT=0
