FROM node:24-alpine AS base

WORKDIR /base

RUN apk add --no-cache curl
RUN npm i -g pnpm turbo
COPY . .

RUN turbo prune backend --docker

FROM base AS builder

WORKDIR /app

COPY --from=base /base/out/json .
COPY turbo.json .
RUN pnpm install --prod --frozen-lockfile
COPY --from=base /base/out/full .

CMD ["pnpm", "--filter", "backend", "start"]
