FROM node:22-alpine AS base

WORKDIR /base

RUN apk add --no-cache curl
RUN npm i -g pnpm turbo
COPY . .

RUN turbo prune backend --docker

FROM base AS builder

WORKDIR /app

COPY --from=base /base/out/json .
COPY turbo.json .
RUN pnpm install --frozen-lockfile
COPY --from=base /base/out/full .

RUN pnpm build

RUN rm -rf node_modules
RUN pnpm -r exec rm -rf node_modules
RUN pnpm install --prod --frozen-lockfile

CMD ["pnpm", "--filter", "backend", "start"]
