### Sign Up
POST http://localhost:3333/auth/sign-up
Content-Type: application/json

{
  "name": "John Doe1",
  "email": "johna.doe1@examaple.com",
  "password": "password123"
}

### Sign In
POST http://localhost:3333/auth/sign-in
Content-Type: application/json

{
  "email": "johna.doe1@examaple.com",
  "password": "password123"
}

### Create Password
POST http://localhost:3333/passwords
Authorization: Bearer K5Xd12JlIrbZEPJUKMv30hFDlBG6P8co
Content-Type: application/json

{
  "name": "Example1",
  "login": "example_login1",
  "siteUrl": "https://example.com1",
  "password": "example_password1"
}

### Get Saved Passwords
GET http://localhost:3333/passwords
Authorization: Bearer K5Xd12JlIrbZEPJUKMv30hFDlBG6P8co

### Get Password by ID
GET http://localhost:3333/passwords/b6b7e259-550a-49c1-9e36-46d94c9ccb58
Authorization: Bearer K5Xd12JlIrbZEPJUKMv30hFDlBG6P8co

### Update Password
PATCH http://localhost:3333/passwords/b6b7e259-550a-49c1-9e36-46d94c9ccb58
Authorization: Bearer K5Xd12JlIrbZEPJUKMv30hFDlBG6P8co
Content-Type: application/json

{
  "name": "Updated Example2",
  "login": "updated_login2",
  "siteUrl": "https://updated-example.com",
  "password": "updated_password"
}

### Delete Password
DELETE http://localhost:3333/passwords/b6b7e259-550a-49c1-9e36-46d94c9ccb58
Authorization: Bearer K5Xd12JlIrbZEPJUKMv30hFDlBG6P8co