FROM node:24-alpine AS base

WORKDIR /base

RUN apk update
RUN apk add --no-cache libc6-compat
RUN npm i -g pnpm turbo

COPY . .
RUN turbo prune desktop --docker

FROM base AS builder

WORKDIR /app

COPY --from=base /base/out/json .
COPY turbo.json .
RUN pnpm install --frozen-lockfile
COPY --from=base /base/out/full .
RUN pnpm build:web

FROM scratch AS output

COPY --from=builder /app/apps/desktop/dist .

FROM nginx:stable-alpine3.21 AS runner

COPY --from=builder /app/apps/desktop/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
